/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "WaveDAC8.h"
#include "ADC.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "DAC_aliases.h"
#include "DAC.h"
#include "UART_LOG.h"
#include "ISR_UART.h"
#include "Green_LED_aliases.h"
#include "Green_LED.h"
#include "Yellow_LED_aliases.h"
#include "Yellow_LED.h"
#include "Red_LED_aliases.h"
#include "Red_LED.h"
#include "ISR_PB.h"
#include "Push_button_aliases.h"
#include "Push_button.h"
#include "User_LED_aliases.h"
#include "User_LED.h"
#include "WaveDAC8_DacClk.h"
#include "WaveDAC8_Wave1_DMA_dma.h"
#include "WaveDAC8_Wave2_DMA_dma.h"
#include "WaveDAC8_VDAC8.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

